#!/bin/bash
sudo apt-get update
sudo apt-get install docker.io -y
sudo systemctl enable docker.service
sudo systemctl start docker.service
sudo mkdir ak2 && cd ak2
sudo git clone https://github.com/Aparna-SJ/codedeploy-docker.git
sudo cp codedeploy-container/scripts/Dockerfile.txt /opt/codedeploy-agent/
sudo cp codedeploy-container/index.html /opt/codedeploy-agent/
